// app/layout.tsx

import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import Providers from './Providers';
import 'antd/dist/reset.css';

const geistSans = localFont({
	src: './fonts/GeistVF.woff',
	variable: '--font-geist-sans',
	weight: '100 900',
});
const geistMono = localFont({
	src: './fonts/GeistMonoVF.woff',
	variable: '--font-geist-mono',
	weight: '100 900',
});

const pnuArabic = localFont({
	src: [
		{
			path: './fonts/pnu/ArbFONTS-PNU-Light.ttf',
			weight: '300',
			style: 'normal',
		},
		{
			path: './fonts/pnu/ArbFONTS-PNU-Regular.ttf',
			weight: '400',
			style: 'normal',
		},
		{
			path: './fonts/pnu/ArbFONTS-PNU-Medium.ttf',
			weight: '500',
			style: 'normal',
		},
		{
			path: './fonts/pnu/ArbFONTS-PNU-Bold.ttf',
			weight: '700',
			style: 'normal',
		},
		// Add other font weights/styles as needed
	],
	variable: '--font-pnu-arabic',
	display: 'swap',
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html
			lang='ar'
			className={pnuArabic.variable}
		>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#f9f9f9] bg-gradient-to-b from-[#03224e] to-[#f9f9f9] bg-no-repeat [background-size:100%] overflow-x-hidden min-h-screen`}
			>
				<Providers>{children}</Providers>
			</body>
		</html>
	);
}
